### ISSUE TITLE
failed to install add-on from plugin.video.gogoanime-1.3.6.zip file

### ISSUE THREAD

**Issue by wrtboy168** [cywteow/cywteow.github.io#2]
error encountered while manually installing plugin.video.gogoanime-1.3.6.zip on kodi 18.

the dependency on script.module.rerouting version 0.1.2 could not be satisfied.

**Comment by cywteow** [comment]
Hello, since you did not add my repo, it doesn't install the dependency automatically. So you probably need to download this  [dependency](https://github.com/cywteow/cywteow.github.io/blob/master/script.module.rerouting/script.module.rerouting-0.1.2.zip) and install from zip as well then try install from zip with plugin.video.gogoanime-1.3.6.zip again. Please try and let me know if it works.

**Comment by wrtboy168** [comment]
hi and thanks for the reply.  i have added your repo but since i'm still on kodi 18, i'm not able to install the latest version of gogoanime hence i tried manually installing the 1.3.6 version.  i'm able to install gogoanime after installing script.module.rerouting version 0.1.2 zip.  consider ticket closed.  thanks again and stay safe.
